## "Hello, World" 출력
### 주피터 좋네

In [5]:
print("Hello, World")

Hello, World


HW 1-1 Hangul letter with first alphabet letter \n -> 줄바꿈

In [44]:
a="PPP     PPP       PP"
b="PPPPPPPPPPP       PP"
A="PPP     PPP       PPPPPPPP"
c="  PPPPPPPPPPPPPPPPPP"
d="                  PP"
e="                    "
print(a,a,a,b,A,a,b,e,e,c,d,d,d,d,d,sep="\n")

PPP     PPP       PP
PPP     PPP       PP
PPP     PPP       PP
PPPPPPPPPPP       PP
PPP     PPP       PPPPPPPP
PPP     PPP       PP
PPPPPPPPPPP       PP
                    
                    
  PPPPPPPPPPPPPPPPPP
                  PP
                  PP
                  PP
                  PP
                  PP


HW 1-2 백만개 난수 형성(0~9 정수), 나의 학번 뒤의 6글자와 일치하는 확률 구하기, 이론적인 확률과 비교하기 -> 횟수 늘리면서 비교해보기?

for문 { 난수형성 -> for 문 ( array 안에 6개씩 묶기 -> 340027과 비교 -> 있다면 리스트에 1append ) -> len(리스트)  = 일치_개수변수 -> 일치_개수변수를 최종_리스트에 append } -> 최종_리스트의 모든 값 더하고 횟수 x로 나누어서 기댓값 찾기 

In [45]:
import numpy as np
import pandas as pd

def compare(x):  # x에 들어갈 것은 반복 횟수
    Final_count = []
    for i in range(0, x, 1):
        Same_count = []
        RN = np.random.randint(10, size=1000000)
        for j in range(0, 1000000 - 5):  # 뒤에서 6번째 까지만
            if np.array_equal(RN[j:j + 6], np.array([3, 4, 0, 0, 2, 7])):  # np array 비교
                Same_count.append(1)
        Final_count.append(len(Same_count))
    Expected_value = int(sum(Final_count))
    Result = Expected_value/x
    return print(Result)

compare(5)

1.2


In [46]:
# 이론적인 확률
n=999995
p=0.1**6
print(n*p)

0.9999950000000004


In [47]:
# 자료형 테스트
RN=np.random.randint(10, size=1000000)
for i in range(0,10,1):
    print(RN[i:6])
print(np.array([1,1,1,1,1,1]))
print(type(np.array([1,1,1,1,1,1])))
print((sum(RN)))

[1 7 4 7 7 6]
[7 4 7 7 6]
[4 7 7 6]
[7 7 6]
[7 6]
[6]
[]
[]
[]
[]
[1 1 1 1 1 1]
<class 'numpy.ndarray'>
4499418


HW 1-3 